language: node_js
branches:
  only:
    - master
node_js:
  - "8.9.3"
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run sass-lint
    - script: npm run test
    - stage: build
      script: npm run build
