name: Dist
on:
  push:
    branches:
      - "release/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # update apt cache
      - name: Update apt cache
        run: sudo apt-get update -y
      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "14.21.3"
      - name: Set NPM 7
        run: npm install -g npm@8.3.2
      # Cache node_modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install MDNS build dependencies
        run: sudo apt-get install libavahi-compat-libdnssd-dev -y

      - name: Install node modules
        run: npm install

      - name: Delete current release assets
        uses: Kellojo/delete-release-assets-action@v1.9
        with:
          delete-only-drafts: true
          github-access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Linux build
        run: npm run dist:linux -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
