name: CI
on:
  push:
    branches: [master]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # update apt cache
      - name: Update apt cache
        run: sudo apt-get update -y
      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "14.21.3"
      - name: Set NPM 7
        run: npm install -g npm@8.3.2
      # Cache node_modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install MDNS build dependencies
        run: sudo apt-get install libavahi-compat-libdnssd-dev -y

      - name: Install node modules
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm install

      - name: Lint
        run: npm run lint -- --max-warnings 0 && npm run sass-lint -- --max-warnings 0

      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # update apt cache
      - name: Update apt cache
        run: sudo apt-get update -y
      # Set node version
      - uses: actions/setup-node@v2
        with:
          node-version: "14.21.3"
      - name: Set NPM 7
        run: npm install -g npm@8.3.2
      # Cache node_modules
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install MDNS build dependencies
        run: sudo apt-get install libavahi-compat-libdnssd-dev -y

      - name: Install node modules
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm install

      - name: Build
        run: npm run build
